ryanlelek/Raneto

views/home.html

Simple fix to display the categories better on small screens.
New:
Old:

Better mobile layout

---

app.js
config.js
content/usage/authentication.md
package.json

Add optional basic authentication
Added authentication boolean in config.js, defaults to false
Added credentials to config.js
Add authentication.md to docs

Add optional basic authentication

---

app.js

This would be handy to add custom page templates

Enable custom page templates via meta

---

README.md

Closes #71.
---
(If that is all you meant.)

Update node version in README

---

app/index.js
example/config.default.js
public/scripts/raneto.js
public/translations/de.json
public/translations/en.json
themes/default/templates/edit.html
themes/default/templates/home.html
themes/default/templates/layout.html
themes/default/templates/login.html
themes/default/templates/page.html
themes/default/templates/search.html

Added localization to translate all language specific strings from a single JSON file for each language. English and German included as examples.

Added localization

---

README.md

See issue https://github.com/gilbitron/Raneto/issues/79#issuecomment-177364143

Added vagrant container example to 'Related Projects' in README.

---

app/index.js

Added images folder as an static resource, so that embedded document images are served. 
#88

Fixed bug #88 for embedded images in documents

---

app/index.js

Returned contents of index.md in case it exists.

---

public/translations/de.json
public/translations/en.json

translation: added missing key 'editor' to global section

translation: added missing key 'editor' to global section.

---

app/routes/page.edit.route.js
app/routes/wildcard.route.js
app/translations/de.json
app/translations/en.json
themes/default/public/scripts/raneto.js
themes/default/templates/edit.html

This adds ability to edit meta information for md files (see issue #97 ).
Let me know if there is anything I should improve.

Added ability to edit meta information for md files

---

app/routes/page.edit.route.js

This fixes the warnings when running `make test` (see #98 )

code cleanup (make test passes)

---

app/functions/create_meta_info.js
app/routes/page.edit.route.js

@ryanlelek  followed your advice ;)

moved function create_meta_info to app/functions to ease future testing

---

app/routes/wildcard.route.js
themes/default/templates/page.html

This fixes issue #96.
Let me know if I should refactor this in any way.

page editing for config 'authentication:false' and 'allow_editing:true'

---

app/translations/tr.json

First of all, we'd like to thank you guys for creating such a useful tool.
We've just started to use it and we thought it'd be nice if Raneto has Turkish translations.

Added Turkish translations

---

README.md
themes/default/templates/page.html

Minor modifications . You can use the phone ( or shrink the browser window ) browser , automatically hide the left menu . Otherwise, with the increase of the content of the menu it seems too long.

Automatically hide menu on the left .

---

app/routes/login_page.route.js
app/translations/fa.json
example/config.default.js
gulpfile.js
package.json
themes/default/public/styles/raneto.rtl.css
themes/default/templates/layout.html
themes/default/templates/login.html

the example project strings are hard coded so in order to have translations there too we need to include them into translation files or somewhere inside that example project.
also I added bootstrap-rtl dependency so you need to do a npm install.

Persian (Farsi) & RTL support added

---

.gitignore
app/routes/home.route.js
app/routes/login.route.js
app/routes/logout.route.js
app/routes/search.route.js
app/routes/wildcard.route.js
example/config.default.js
themes/default/templates/layout.html

it's just a fast implementation as we talk before with @ryanlelek. we should somewhere implement registration process and generate a separate "credentials" file.

Added Multiple User Login Feature (iss #114)

---

app/translations/zh.json

Chinese translation zh.json added

add chinese translation

---

app/translations/ptbr.json

Added PT-BR translation to Raneto.
Use ptbr on config to get access to it.

Added PT-BR translation

---

app/index.js
app/routes/sitemap.route.js
package.json

generate sitemap.xml for SEO management

add dynamic sitemap.xml

---

app/routes/wildcard.route.js
example/config.default.js
package.json

Disabled by default
closes #51

Add table of contents support

---

app/functions/create_meta_info.js
package.json

use yaml instead of comment blocks
refs: https://github.com/gilbitron/Raneto/issues/18

create_meta_info saves yaml now

---

app/index.js
app/middleware/always_authenticate.js
app/middleware/error_handler.js
app/routes/home.route.js
app/routes/search.route.js
app/routes/wildcard.route.js
example/config.default.js
themes/default/templates/layout.html

I wanted read only knowledge base but one that admins can edit.

Add ability to authenticate only for edtiing

---

app/index.js
app/middleware/authenticate_read_access.js

This is my proposal for implementing the functionality described in Issue #106.
As far as I see, this is already in line with what the comments in the config file describe.

Implement authentication for accessing knowledgebase content (Issue #106)

---

app/routes/page.create.route.js

Close file only, if file could be openend

---

app/core/lib/raneto.js
app/functions/create_meta_info.js

Updated pull request to adhere to YAML specifications

Fix meta header to prevent broken tables

---

app/index.js
example/config.default.js

to enable this feature just set authentication_for_read to true then only authenticated users can access knowledge base. (issue #169)

Added authentication config for reading (issue #169)

---

README.md

https://github.com/gilbitron/Raneto/issues/125

added docker container setup link

---

app/translations/es.json

Duplicated pull request. Previous one closed. This one with correct target branch. Sorry about the mistake.

Added spanish translation file

---

app/functions/build_nested_pages.js

This pull request brings respect for windows directory separator char. Actually, I'm aware that there are more such places. Probably, I will provide further PRs, if you don't mind :)

build_nested_pages() support windows directory separator

---

app/functions/build_nested_pages.js

Reverts gilbitron/Raneto#216
wrong branch

Revert "build_nested_pages() support windows directory separator"

---

app/routes/wildcard.route.js
themes/default/templates/page.html

This pull request extends functionality brought in #183

Support more nested levels on pages (not just on the homepage)

---

app/translations/ro.json
themes/default/templates/page.html

Hello,
Here is a Romanian translation for use with Renato. Hope this is useful to others.
Marius

added romanian translation

---

themes/default/templates/login.html
themes/default/templates/search.html

Fix an issue on the login page where the jquery backstretch plugin wasn't loading correctly.

Backstretch 404

---

app/translations/pl.json

I don't think anything is needed to add.
Cheers.

Add polish translation

---

package.json

add heroku postinstall script for gulp

add heroku postinstall script for gulp

---

app/translations/da.json

Danish translation

---

app/translations/sv.json

Swedish translation.
The json file is created with ISO 639-1 in mind.
/Synt3x

Swedish translation

---

themes/default/templates/page.html

Solution found by @GrahamDumpleton in https://github.com/gilbitron/Raneto/issues/286
Tested this change with linuxserver.io docker image of Raneto v0.16.4.

Side menu not showing up

---

README.md
example/content/install/installing-raneto.md
example/content/updates/updating-raneto.md

Addresses a part of issue #324 and also makes the readme and update guide more readable.

Docs updates

---

themes/default/templates/layout.html

Fix for https://github.com/gilbitron/Raneto/issues/329

fix 404 due to wrong fitvids js location

---

example/config.default.js

Fix: Example configuration file

---

package-lock.json
package.json

Release: v0.16.6

---

package.json

Release: v0.17.0

---

app/routes/wildcard.route.js

Edit: Adding suggestion in #340

---

app/routes/wildcard.route.js
example/config.default.js

Implementing fix in #310 
Quick testing worked fine for default configs as well as the edits

Fix: for Issue #310

---

themes/default/templates/layout.html

Fixes the issue where the search and log in button get wonky on resize.
Fixes #357

fixed responsive top bar issues

---

app/translations/fi.json

Translator: Atte "Mixerboy24" Oksanen / LocalghostFI Ltd

Finnish translation

---

package.json

2022.08.02 / v0.17.1
====================
* **[SECURITY]** Sanitization, DoS, Best Practices by @J-GainSec #368
-- Mitigation @ryanlelek #370
* **[New]** Finnish Translation by @Mixerboy24 #363  Oksanen / LocalghostFI Ltd
* **[Fix]** Redirect Fix on server restart, suggested by @leofranke95 #340
* **[Fix]** Docker image build process by @jj-style #355
* **[Fix]** Top bar navigation by @norogoth #357 #358
* **[Fix]** Add Page to Current Category @Meiwer #364
Fully up to date modules as of 2022-08-02
(except 3 held modules due to breaking changes)
-- Ryan

Release: v0.17.1
