ryanlelek/Raneto

views/home.html, views/layout.html, views/page.html, views/search.html
I set up Raneto using a proxy pass in some folder on my web server, but the URLs were always absolute to the root directory, not aware of the `config.base_url` value. This PR solves this.
=> Use `config.base_url` in all views.

app.js
Marked generates html classes with the language hint for the parser by default using the 'lang-' prefix on the class name, however highlight.js does not support this.
So even though one hints in one's own markdown files which language it is, highlightjs will ignore it and try to automatically detect (usually wrongly) because it's just looking for the language as a classname on the code block (see here: http://highlightjs.readthedocs.org/en/latest/css-classes-reference.html).
Overriding the prefix in the marked options makes it render properly for highlightjs.
=> highlight.js doesn't use the 'lang-' prefix

public/scripts/raneto.js
Non-Latin characters in Category or Article names are encoded within
page address and should be decoded back before sending page saving
request to API. Resolves #61.
=> Decode URI before saving for non-Latin characters

app/index.js, public/scripts/raneto.js, themes/default/templates/page.html
There are changes to resolve #70
1. Added 'Main articles' header into menu to keep interface consistent
with other categories
1. If category name for page being saved is 'Main articles' then we send
empty category name in request to API
1. If backend API receives empty category name then it creates or
updates file in root of content directory
=> Adding new page in 'Main articles'

app/index.js, public/scripts/raneto.js, themes/default/templates/layout.html, themes/default/templates/page.html
This would close #77 by enabling authentication only for actions that modify content, like editing, deleting or creating pages and categories.
I also added a fallback redirect for ajax requests in `public/scripts/raneto.js` in case the session is expired or else.
Though it is not possible to keep the current functionality of requiring authentication for each page.
=> Auth on changes only

.editorconfig, app/functions/create_meta_info.js, themes/default/public/styles/login-style.css
This adds an `.editorconfig` to standardise 2-space indenting, and I've gone through and replaced any tab indentation with spaces for non-lib code.
Fix #104
=> Add editorconfig, convert all tabs to spaces

app/index.js
I'm using Raneto in its library form (`require('raneto');`). I'd like to use the default template until I'm ready to write my own. Line 52 here allows me to not set a public_dir and still serve the default template static files.
In the case where I have my own public directory, but I'm not overriding all of the default files, I still need to serve the default theme directory stuff or copy it. It makes sense to also serve that, as on lines 67-68.
=> Allow use of default theme as public directory

Dockerfile
This lets you simply:
```#!bash
docker build -t raneto .
docker run -d -e VIRTUALHOST=kb.mydomain.com -e PORT=3000 raneto
```
The configeration above is only an example and uses
[autodock-paas](https://github.com/prologic/autodock-paas)
Otherwise just: `docker run -d -p 3000:3000 raneto` and hit http://<ip_of_docker_host>:3000/
=> Adds Docker deployment support to Raneto

app/raneto-core/lib/raneto.js, app/raneto-core/src/raneto.js, example/config.default.js, test/raneto-core.test.js
This will replace %variable_name% with Variable Content.
The code will only run if config.variables exists.
The name should not include %'s.
Closes #42
=> Add support for custom variables

app/raneto-core/lib/raneto.js, app/raneto-core/package.json, app/raneto-core/src/raneto.js, package.json
We're already using js-yaml in Raneto, just switching core from yamljs
to js-yaml to remove a dependency.
=> Switch from yamljs to js-yaml in core

app/functions/get_last_modified.js, app/routes/home.route.js, app/routes/sitemap.route.js, app/routes/wildcard.route.js, example/config.default.js, example/content/usage/page-meta.md, test/content/page-with-bom-yaml.md, test/functions.test.js
This gives us the ability to override the file system's last modified date by adding an optional `Modified:` yaml variable. According to the (YAML spec)[http://yaml.org/type/timestamp.html], the datetime should be an ISO 8601 datetime.
This also requires a time (with timezone offset) attached to it. The reason why is because YAML interprets a date with no time as 00:00:00-0000. That means that when the datetime is loaded, it could select the previous day as the date. ie: 2010-01-01 gives us 2010-01-01T00:00:00-0000, which when converted into a datetime with YAML, then gives us 2009-12-31T19:00:00-0500.
Closes #69.
=> Add optional modified yaml

app/routes/sitemap.route.js
It was giving a ".endsWith is not defined" for the file path string, so I went back to simple js and it just worked for CentOS 6.3
=> Making sitemaps works properly on unix based systems.

app/core/lib/raneto.js, app/core/src/raneto.js, app/functions/build_nested_pages.js, app/routes/home.route.js, test/content/sub/sub2/sub2_page.md, test/functions.test.js, themes/default/templates/home.html
I needed to group the content on the Raneto main page and I created a function to modify pages array for home route. For this I've added a flag (`is_directory`) for new page objects and modified home template so it renders correctly. 
This will also allow to create nice navigation tree menu in the navbar. Something like that was mentioned in #166.
Maybe it should be configurable and what method of showing content should be default then?
Here is example of the results:
=> Build nested pages from content directory

app/middleware/oauth2.js
I'm using Raneto with Google OAuth 2 authentication but I want to limit access to users from our company domain. 
So, I created the config.oauth2.validateHostedDomain to define this behavior. I not sure if this is the best way to do that but solved for us. 
Also, hostedDomain is not working today, as stated by #198. I changed to use the config as is in the example config and to pass on authenticate method because the strategy options are not passed to authorizationParams by passport.
=> Validate hostedDomain when using Google OAuth2

app/routes/search.route.js, test/content/special-chars.md, test/raneto-core.test.js
This PR fixes #215, I changed from `validator.escape`, which encoded some special characters and that was breaking the search. This problem could be fixed in two ways: allowing searches with special characters or stripping them from the query. I choose the latter one, since that wouldn't not send the characters to Lunr.
=> Fixes search with special characters

gulpfile.js, package.json, themes/default/templates/login.html
I would like to propose to switch from SweetAlert to [SweetAlert2](https://github.com/sweetalert2/sweetalert2) - the supported fork of SweetAlert. The original reason for creating SweetAlert2 is the inactivity of SweetAlert: https://stackoverflow.com/a/27842854/1331425 
1. No need to care about styles, they are injected automatically  
2. Accessibility (WAI-ARIA) - SweetAlert2 is fully WAI-ARIA compatible and supports all popular screen-readers. Accessibility is a must in 2017, there are a lot of explanatory and tech articles, but this one is truly inspirable: [Software development 450 words per minute](https://www.vincit.fi/en/blog/software-development-450-words-per-minute/)
3. Better buttons contrast is a huge advantage for all users especially for users with vision disabilities. 
4. …
=> Switch from SweetAlert to SweetAlert2

themes/default/templates/search.html
When file is a the root of the content, it displays under the Main Article section.
A search that returns one of those files shows the page excerpt as blue text that is a link.
When the artilce is at the root, it doesn't have a category.
The <a> tag is started unconditionally, but the the end </a> tag is only there when there is a category.
I've formatted the code to better see the conditions as well as fix the issue.
=> Search result displays page-excerpt as link when it is a "Main Article" 

README.md
Missing to run gulp task before first start caused 404 errors on some static resources.
#251 
#194
=> Run gulp task before first start. Fixed #251 #194

app/index.js, app/middleware/always_authenticate.js, app/middleware/authenticate.js, app/middleware/authenticate_read_access.js, app/routes/login_page.route.js, app/routes/logout.route.js, app/routes/page.create.route.js, themes/default/public/scripts/login.js, themes/default/public/scripts/raneto.js, themes/default/templates/layout.html, themes/default/templates/login.html
This address problems raised in #200, #279 and also most likely #189.
Specifically, when ``base_url`` was being set, any URLs generated from the Javascript running in the browser was not including the ``base_url`` value.
For the login page, the ``config`` object was also not being passed in when rendering. This was needed as the template file was trying to access it to use ``base_url`` in links in the HTML generated from the server.
The changes should result in the following now working correctly when ``base_url`` is used.
* Login.
* Page editing.
* Translations.
Note that this only fixes the authentication using forms based login. I haven't tried to address login using Google OAuth, as I am not setup to test that at the moment. Suggest that any changes related to making Google OAuth work …
=> Fix issues with login, editing and translations when base_url is set.

app/routes/wildcard.route.js, example/config.default.js
This adds an attribute `table_of_contents_options` to Raneto's config file and passes it to [markdown-toc](https://www.npmjs.com/package/markdown-toc).
If the attribute is not specified in the config file, `undefined` is passed to markdown-toc which results in the same behavior as before.
Fixes #303
=> Allow configuration of table of contents via config file

app/index.js, app/routes/wildcard.route.js
=> Correctly use 404 error.html template when necessary. Don't throw 404 for pages that actually exist. (fixes #264 and #265)

app/index.js, example/multiple-instances.js
Solves #189 
To test:
- Clone repo
- `make start`
- Validate service on `http://localhost:3000/`
- Edit `example/config.default.js` to `base_url: '/mydocs',`
- Restart service
- Validate service on `http://localhost:3000/mydocs/`
- Stop service
- Validate multi-host of service by running `node example/multiple-instances.js`
- Validate service on `http://localhost:3000/en/` and `http://localhost:3000/es/`
^ Note that the multiple-service script passes a `nowrap` setting to prevent a double-wrap, one from `app/index.js` and the other in the `multiple-instances.js` script itself, which would lead to `http://localhost:3000/en/en/`
=> Fix: #189 Respect base_url setting and serve content and assets

app/core/contents.js, example/content/usage/category-meta.md
You can now add a meta description to the categories, to be used in the templates, for example in the homepage to further add details to each group of links.
=> Add description in the meta categories file

app/middleware/oauth2.js, example/config.default.js, package-lock.json, package.json
Added feature that restricts access to Raneto only to the selected google group.
Useful if you want to limit acceess to your knownledge base only to curated list of members of your organization.
In order to use it, you need to enable AdminSDK access for your Google application, and generate API key, that needs to be pasted in confg file
=> Added Google groups restriction feature

app/index.js, example/content/install/production-notes.md, example/multiple-instances.js, example/server.js
**Updates to fix #344**
- Default listening address is now `127.0.0.1` instead of all interfaces.
- Override is allowed by specifying `HOST` environment variable.
- Allowed values of `HOST` are anything the core Node.js net server listener can handle. [docs link](https://nodejs.org/api/net.html#net_server_listen).
**Netstat Output**
Before: `TCP *:3000 (LISTEN)`
After: `TCP 127.0.0.1:3000 (LISTEN)`
**Possible issues**
- EnvVar Name
- Multiple IPs (IPv4/IPv6) addresses
Requested by @meepmeep
=> New: Defaulting listening IP address and adding override

.dockerignore, Dockerfile, package.json
Fix #354 unable to build docker container.
Add `gulp` to normal node dependencies as currently not installed with `npm install --production` flag but is necessary to run with `npm start` in the container.  
Add dockerignore file  to ignore `node_modules` and other larger directories which slow down the docker build from `COPY . /usr/src/app`.  
Bind on `0.0.0.0` so Raneto can be accessed from outside the container if the port is forwarded.
I have tested mounting a local content folder into the container at `/usr/src/app/example/content` and it works as expected.
=> fix local docker build and run

app/core/contents.js, package.json, test/content/sub/hidden/not_on_menu.md
There was old support for ignoring directories in listing: https://github.com/gilbitron/Raneto-Core/commit/d74a0e1b7ef4688b965737807946f3585e6253ac
but it was crashing when attempting to use it.
This PR adds it to test content and fixes the crash.
=> Fix support for ignored directories

app/core/contents.js, app/routes/wildcard.route.js, config/config.js, content/pages/usage/category-meta.md, content/pages/usage/page-meta.md, content/pages/what-is-raneto.md, test/content/hidden-page.md, test/content/sub/not_on_home/meta, test/raneto-core.test.js
Following the example of https://github.com/ryanlelek/Raneto/pull/223/commits from @dgarcia202 I've added a "ShowOnMenu" options, to allow to filter which pages can be present on the menu and which one shouldn't. In this case too, all pages behave following a default setting, and are visible in not set otherwise.
When the page is not visibile in the site menu, it is still active and visible by visiting the url. 
I've also updated the test to include the new feature, using the existing one as a guideline.
=> ShowOnMenu can now be used to show and hide pages on the site menu
